### ISSUE TITLE
'author' is not customisable

### ISSUE THREAD

**Issue by notoriousturtle** [ronv/lines#2]
It's not possible to modify the 'author' value and have it reflect the author of the blog.

Still include Ronald as the author of base template (as people modify it), just include it below the author of the blog or something.

**Comment by ronv** [comment]
Hi, Are you talking about meta tag "author"? If so, you can edit this file: https://github.com/ronv/lines/blob/master/layouts/partials/head.html and remove it.

Br, Ron

**Comment by notoriousturtle** [comment]
That fixed it. I probably should have read more of the Hugo documentation beforehand! Thanks! Great layout by the way :)
